#
# Cookbook Name:: wawision
# Build:: .kitchen.yml
#
# Author:: Stephan Linz <linz@li-pro.net>
#
# Copyright:: 2015, Li-Pro.Net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# See details for Test Kitchen's YML Syntax on:
# https://docs.getchef.com/config_yml_kitchen.html

driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.0.3
  data_path: test/shared
  data_bags_path: test/fixtures/data_bags
  roles_path: test/fixtures/roles

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: centos-6.5
    run_list:
      - recipe[yum::default]

suites:
  - name: default
    run_list:
      - recipe[wawision::default]

  #
  # Application bootstrap suites
  #
  - name: wawision_app_defaults
    run_list:
      - recipe[wawision_app::default]
  - name: wawision_app_overrides
    run_list:
      - role[wawision_test_overrides]
      - recipe[wawision_app::default]

# vim: ts=2 sts=2 sw=2 ai si et ft=yaml
